//
// Created by Ivan Bogatyrev on 12/17/2020.
//

#ifndef LAB_03_ERRORS_H
#define LAB_03_ERRORS_H

#define IO_ERROR_INPUT_FROM_KEYBOARD 11
#define IO_INVALID_ROWS_NUMBER 12
#define IO_INVALID_COLUMNS_NUMBER 13
#define IO_ELEMENTS_LIMIT 14

#define MEMORY_ALLOCATION_ERROR 21

#endif //LAB_03_ERRORS_H
