//
// Created by Ivan Bogatyrev on 12/14/2020.
//

#ifndef LAB_02_ERRORS_H
#define LAB_02_ERRORS_H

#define FILE_NAME "students_data.txt"

#define INVALID_INPUT_DATA 1

#define IO_ERROR 2
#define IO_FILE_SIZE_ERROR 21
#define IO_TABLE_DATA_READ_ERROR 23
#define IO_DATE_FORMAT_ERROR_DAY 241
#define IO_DATE_FORMAT_ERROR_MONTH 242
#define IO_DATE_FORMAT_ERROR_YEAR 243
#define IO_DATA_FORMAT_ERROR_DORMITORY 25
#define IO_DATA_FORMAT_ERROR_ADDRESS_STREET 261
#define IO_DATA_FORMAT_ERROR_ADDRESS_HOME 262
#define IO_DATA_FORMAT_ERROR_ADDRESS_APRT 263

#define TABLE_EXCEPTION 3
#define TABLE_IS_EMPTY 31

#define MEMORY_ALLOCATION_ERROR 3

#endif //LAB_02_ERRORS_H
