#define INTEGER_INPUT_ERROR -20
#define INTEGER_WRONG_FORMAT -21
#define INTEGER_TO_EXPON_ERROR -23

#define FLOAT_INPUT_ERROR -30
#define INPUT_FORBIDDEN_SYMBOL -31
#define INPUT_E_ERROR -32
#define INPUT_SIGN_ERROR -33
#define INPUT_DOTS_IN_DEGREE -34
#define FLOAT_DATA_INVALID -35
#define INPUT_DOTS_IN_MANTISSA -36

#define PARSING_MANTISSA_ERROR -41
#define PARSING_DEGREE_OUT_RANGE -42
#define PARSING_RANGE_ERROR -43
#define PARSING_OVERFLOW -44


